# --- .github/workflows/build-deploy.yml ---

# İş akışının adı (GitHub Actions arayüzünde görünür)
name: CI Pipeline - Build Application

# İş akışını tetikleyecek olaylar
on:
  # 'main' branch'ine doğrudan push yapıldığında
  push:
    branches: [ main ]
  # 'main' branch'ine yönelik bir Pull Request açıldığında, güncellendiğinde veya kapatıldığında (birleştiğinde)
  pull_request:
    branches: [ main ]
    types: [ opened, synchronize, reopened, closed ] # 'closed' ve 'merged' kontrolü ile sadece birleşince çalışması sağlanabilir

# İş akışındaki işler (jobs)
jobs:
  # 'build-application' adında bir iş (job)
  build-application:
    # İşin çalışacağı işletim sistemi ortamı
    runs-on: ubuntu-latest

    # İşin adımları (steps)
    steps:
      # 1. Adım: Depodaki kodu çalışma ortamına kopyala
      - name: Checkout code
        uses: actions/checkout@v4 # Standart checkout action'ı

      # 2. Adım: Java Geliştirme Kiti'ni (JDK) ayarla
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Kullandığınız Java sürümüyle eşleşmeli
          distribution: 'temurin' # Güvenilir bir JDK dağıtımı
          cache: maven # Maven bağımlılıklarını önbelleğe alarak derleme süresini iyileştirir

      # 3. Adım: Maven ile uygulamayı derle ve paketle (JAR oluştur)
      - name: Build with Maven
        # '-B' batch modunda çalıştırır (interaktif olmayan)
        # 'package' hedefi derleme yapar ve target/*.jar dosyasını oluşturur
        run: mvn -B package --file pom.xml

      # 4. Adım: Oluşturulan JAR dosyasını bir 'artifact' olarak yükle
      # Artifact'lar, iş akışının sonraki adımlarında veya manuel indirme için kullanılır
      - name: Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: application-jar # Artifact'a verilecek isim
          path: target/*.jar # Yüklenecek dosyanın yolu (Maven varsayılan olarak target klasörüne oluşturur)
          if-no-files-found: error # Belirtilen yolda JAR dosyası bulunamazsa iş akışını başarısız yap